# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bakirapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bakirapp
  pod 'Alamofire', '~>4.4.0'
  pod 'SwiftKeychainWrapper', '~>3.0.1'
  pod 'Charts', '~> 3.0.2'
  pod 'SDWebImage', '~> 4.0.0'  
end
