# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=300)),
                ('merchant_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('longitute', models.DecimalField(decimal_places=10, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.MerchantType'),
        ),
    ]
