# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20170610_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='IBAN',
        ),
    ]
