# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_account_iban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
