# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20170610_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'type_icons'),
        ),
    ]
