# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transactiontype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'mtype_icons'),
        ),
    ]
