# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsnapshot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='transactions.Account'),
        ),
    ]
