# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20170610_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
