# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20170610_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='longitute',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
